stages:
- build
- test

build1:
  stage: build
  tags:
    - shell
  script:
    - echo "Do your build here"

test1:
    stage: test
    script:
        - echo "Do a test here"
        - echo "For example run a test suite"
